version: '3.1'
services:
  reservation:
      build:
        context: api.reservation
      ports:
        - "11769:80"
      depends_on:
        - mysql
  vols:
      build:
        context: api.vols
      ports:
        - "11770:80"

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db   

  mysql:
    image: mysql:8.0.31-debian
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mrp
    ports: 
      - 3306:3306
    volumes:
    - mysql-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
  mongodb_data_container :
